name: MagicMemories Python Setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Test with unittest
        run: |
          python -m unittest

           - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        uses: docker/login-action@v1.8.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: http://docker.magicmemories.com
          # Username used to log against the Docker registry. Set the value in Github Repo Secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry. Set the value in Github Repo Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Log out from the Docker registry at the end of a job
          logout: false

      - name: Docker Setup Buildx
        # You may pin to the exact commit or the version.
        # uses: docker/setup-buildx-action@154c24e1f33dbb5865a021c99f1318cfebf27b32
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      # Pass your docker.mm repo and Configure the NEXUS_CREDS in Github Repo Secrets
      - name: Docker Build
        run: | 
          docker build -t docker.magicmemories.com/{{YOUR DOCKERMM REPO}}:${{ github.sha }} --build-arg NEXUS_CREDS=${{ secrets.NEXUS_CREDS}} --push .  
  
  deploy_to_test_env:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Decrypt SOPS Secrets
          # You may pin to the exact commit or the version.
          # uses: rmb938/sops-decrypt-action@b566d1bdf324e157c70890efda8192fd59f18945
          # follow folder structure from :https://github.com/rmb938/sops-decrypt-action
        uses: rmb938/sops-decrypt-action@0.1.0
        with:
          # The directory that contains sops encrypted secrets
          secrets-directory: test

# TODO
      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          command: helm upgrade --install -f helm/values.yaml -f helm/test/decrypted/secrets.test.yaml --namespace test githubactions --set image_tag=${{ github.sha }} ./helm
 