name: conventional commit check

on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Commitsar Action
        uses: aevea/commitsar@v0.16.0
